kind: DeploymentConfig
apiVersion: v1
metadata:
  name: hello-world
  namespace: l-was
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - name: hello-world
          image: 'hello-world:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
