apiVersion: v1
kind: BuildConfig
metadata:
  name: hello-world-build
  namespace: l-was
spec:
  source:
    git:
      ref: ocp3-jenkins
      uri: 'https://github.com/TechNetDemo/l-was'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "hello-world:latest"
